export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const REMOVE_AUTH_LOADING = "REMOVE_AUTH_LOADING";
export const LOGOUT_USER = "LOGOUT_USER";
