export const MLN_LIST = 'MLN_LIST'
export const GET_MLN_BY_ID = "GET_MLN_BY_ID";
export const GET_MLN_WITHOUT_REFERALS_BY_ID = "GET_MLN_WITHOUT_REFERALS_BY_ID";
export const GET_MLN_REFERALS_BY_ID = "GET_MLN_REFERALS_BY_ID";