export const GET_ALL_USERS = 'GET_ALL_USERS'
export const USERS_LOADING = 'USERS_LOADING'
export const REMOVE_USERS_LOADING = 'REMOVE_USERS_LOADING'
export const  GET_USER_DETAIL="GET_USER_DETAIL"
export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const  DELETE_USER="DELETE_USER"
export const  SEARCH_USER="SEARCH_USER"

