export const GET_APPROVED_DOCUMENTS="GET_APPROVED_DOCUMENTS"
export const GET_PENDING_DOC_lIST = 'GET_PENDING_DOC_lIST'
export const PENDING_DOC_LOADING = 'PENDING_DOC_LOADING'
export const REMOVE_PENDING_DOC_LOADING = 'REMOVE_PENDING_DOC_LOADING'

export const DELETE_PENDING_DOC = "DELETE_PENDING_DOC";
export const DELETE_APPROVED_DOC = "DELETE_APPROVED_DOC";
export const GET_PENDING_DOC_BY_ID = "GET_PENDING_DOC_BY_ID";
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
