export const SUB_CATEGORY_LOADING = "SUB_CATEGORY_LOADING";
export const REMOVE_SUB_CATEGORY_LOADING = "REMOVE_SUB_CATEGORY_LOADING";
export const GET_ALL_SUB_CATEGORIES = "GET_ALL_SUB_CATEGORIES";
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";
export const CREATE_SUB_CATEGORIES = "CREATE_SUB_CATEGORIES";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const REMOVE_SUB_CATEGORY = "REMOVE_SUB_CATEGORY";
