export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING'
export const REMOVE_CHANGE_PASSWORD_LOADING = 'REMOVE_CHANGE_PASSWORD_LOADING'

export const GET_ALL_SUB_ADMINS_lIST = 'GET_ALL_SUB_ADMINS_lIST'
export const UPDATE_PASSWORD = "UPDATE_PASSWORD"