export const GET_ALL_QUESTIONAIRE = 'GET_ALL_QUESTIONAIRE'
export const QUESTIONAIRE_LOADING = 'QUESTIONAIRE_LOADING'
export const REMOVE_QUESTIONAIRE_LOADING = 'REMOVE_QUESTIONAIRE_LOADING'
export const ADD_QUESTION = "ADD_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const GET_QUESTION_BY_ID = "GET_QUESTION_BY_ID";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const SEARCH_QUESTIONS = "SEARCH_QUESTIONS"
